### PR TITLE
Updated README.txt (and renamed to README.md), manifest.xml, CHANGES.txt and added CONTRIBUTIONS.txt to README.md

### PR DESCRIPTION
**Pull request by iionly**
- [x] Squash the commits

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
What's the motivation for combining the files? I'd like to keep the changelog in it's own file.

The files should also be converted to markdown syntax. Github will parse them automatically.

**Comment by iionly** [comment]
It's the way I usually do it. That's more or less the only reason.

**Comment by iionly** [comment]
Better?

**Comment by juho-jaakkola** [comment]
Yes, better. One more thing, could you squash the commits together?

**Pull request merged**
