### PR TITLE
Revision of widgets code plus adding support of Widget Manager plugin and index page widget

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by iionly** [comment]
For Elgg 1.9 there's a modification in start.php necessary to get it working correctly with widget manager. Instead of

``` php
elgg_register_plugin_hook_handler('widget_url', 'widget_manager', "event_calendar_widget_urls", 498);
```

it has to be

``` php
elgg_register_plugin_hook_handler("entity:url", "object", "event_calendar_widget_urls");
```

Within the callback function no changes are necessary and the priority is also no longer necessary (it was only necessary because the widget manager plugin on 1.8 did register some - wrong - title urls but the 1.9 version no longer does it).

**Comment by juho-jaakkola** [comment]
I dislike having plugin-specific features hard-coded.

What would you think about adding those to a separate plugin, whose sole purpose is to add features specific for the Widget manager plugin?

**Comment by iionly** [comment]
Best would be if the Widget Manager plugin would be made a core plugin (either replacing custom_index aka the Frontpage plugin or at least be added additionally). Then it wouldn't be an issue with adding index page and group page widgets to be used via the Widget Manager plugin. And I don't see any other option for a non-coder to get a nice index page and/or group pages configurable via drag+drop if not using the Widget Manager plugin.

For all my plugins I've added index page and group page widgets for the Widget Manager plugin in the same way as done here. It's the if-clause checking for the Widget Manager plugin being installed that might be a bit annoying. But the code for the widgets itself and the title link callback function will not interfere if the Widget Manager plugin is not installed.

I don't know if making a separate plugin would be the better option. If there would be separate plugins for every single widget for different plugins it could be a lot of additional plugins to deal with. And if a single separate plugin for all widgets would be created the user wouldn't gain anything either because in this case this plugin would have to check for every single widget to be added if the corresponding plugin is installed.

**Comment by iionly** [comment]
@juho-jaakkola How to proceed? Usage of Widget Manager would be an option and not a requirement. Pull it in or not?

**Comment by juho-jaakkola** [comment]
I guess this is fine.

**Pull request merged**
