### PR TITLE
Tinymce correctly displayed on add/edit event page

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by iionly** [comment]
Don't merge yet.

Problem is that without these changes the longtext field on the event edit page is misplaced with Tinymce editor version 4.X (e.g. my extended_tinymce plugin). But with these changes the editor is misplaced when using the bundled Tinymce plugin of Elgg 1.8 (which's still on tinymce 3.X).

I had not tested with the bundled tinymce before. Now I need to get it working correctly for both versions.

**Comment by iionly** [comment]
Should be ready to merge now.

Now the long description field on the edit event page looks right both with the bundled Tinymce plugin used and with a Tinymce plugin that comes with version 4.X of the editor.

**Comment by juho-jaakkola** [comment]
This PR needs to be rebased on latest 1.8 branch

**Comment by iionly** [comment]
Rebase done.

**Pull request merged**
