### PR TITLE
Code cleanup of actions

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by iionly** [comment]
@juho-jaakkola Why is the "Replaces deprecated jQuey fancybox with colorbox" commit showing up here? I've made my commit for the 1.8 branch and as far as I know your modification is for the 1.9 (or newer) branch only?

**Comment by juho-jaakkola** [comment]
Are you 100% sure the upstream branch was correct? Perhaps you made a branch named 1.8 but accidentally checked out the 1.9 branch to it from upstream?

**Comment by iionly** [comment]
I did create a 1.8 branch and then merged upstream/1.8 into it - surely NOT 1.9 as I re-checked this when your commit showed up. In the following I created the branches for the PRs from the local 1.8 branch.

**Comment by iionly** [comment]
Was the error of me to do

git checkout -b 1.8

followed by

git merge upstream/1.8

instead of

git checkout -b 1.8 upstream/1.8

(if this works)

I think when doing the "git checkout -b 1.8" I have been in a local 1.9 branch (to which I had merged upstream/1.9 before)?

**Comment by juho-jaakkola** [comment]
Yes, that's the mistake. You created 1.8 from the 1.9 branch, so it got all the commits of 1.9. When you did `git merge upstream/1.8` it simply added any 1.8 commits _on top_ of the existing 1.9 commits.

You should had done either:

```
git checkout -b 1.8 upstream/1.8
```

or

```
git checkout -b 1.8
git reset --hard upstream/1.8
```

**Comment by iionly** [comment]
I've fixed the error for this PR - and will do the same for the other 18...........

**Comment by juho-jaakkola** [comment]
18... ouch.

**Pull request merged**
