### PR TITLE
Updated fullcalendar jquery plugin to version 1.6.4

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by iionly** [comment]
Version 1.6.4 is the latest 1.X version of fullcalendar jquery plugin available. There are a lot of newer 2.X versions but API is not compatible (would require changes in Event Calendar plugin).

**Comment by juho-jaakkola** [comment]
How much have you tested the new plugin?

**Comment by iionly** [comment]
Not tested specifically and throrougly the fullcalendar plugin but instead used the "full view" and the other views during testing / cleaning up the code. So far I've not noticed any issues. And if there are any it's maybe not necessarily due to the fullcalendar plugin version but more likely due to the Event Calendar plugin code.

Kevin's version of Event calendar contains version 1.5.3 of the fullcalendar jquery plugin. Already the changelog for the version following v1.5.3 seemed relevant for the future use within Elgg:
'''
v1.5.4
- made compatible with jQuery 1.8.\* (thx @archaeron)
  '''
  Full changelog is at https://github.com/arshaw/fullcalendar/releases. Version 2.x of the fullcalendar plugin would certainly require rewriting of code within the Event Calendar plugin (though it would offer nice new features like Internationalization and timezone support bult-in). Maybe rewriting is  something to do at a later time. Right now I think it would be best to use the latest available 1.X release as long as it still works.

**Comment by juho-jaakkola** [comment]
Ok, let's fix any issues if/when they appear.

**Pull request merged**
