### PR TITLE
Improved spanish translation and fix

### PR DESCRIPTION
**Pull request by Yaco**
I updated the translation using Lorea version. I also fixed an error in the Japanese file that prevented user settings page to load.

### CODE REVIEW

**Comment by iionly** [comment]
The error in the Japanese language file is due to a faulty merge on a previous pull request that introduced the additional characters. The correct language file content shouldn't use add_translation() anymore for the Elgg 1.9 version of the language files - both the Japanese and also not the Spanish. It might be best to change this in the PR accordingly.

May I ask if you updated the Spanish language file to take into account the changes recently made in the Event Calendar plugin, i.e. removing obsolute language strings and adding translations for newly introduced strings. Or is it just the unmodified language file of the Lorea version of Event Calendar? In case of the latter, would it be possible for you to provide the translations for the new language strings?

**Comment by Yaco** [comment]
I just removed 'add_translation()'. The spanish file includes the translations of the strings for event_calendar:notify:*

**Comment by iionly** [comment]
I've checked the completeness of your Spanish language file and found both obsolete strings (no longer used by Event Calendar after the recent updates) and missing strings (strings added by the recent updates). Maybe you want to update the Spanish translations?

Obsolete strings:

event_calendar:no_such_event_edit_error
event_calendar:manage_event_description
event_calendar:end_date_label
event_calendar:end_date_description
event_calendar:start_time_label
event_calendar:start_time_description
event_calendar:end_time_label
event_calendar:end_time_description
event_calendar:show_events_title
event_calendar:cancel
event_calendar:groupprofile
event_calendar:view_calendar
event_calendar:site_wide_link
event_calendar:view_link
event_calendar:edit_link
event_calendar:delete_link
event_calendar:add_to_the_calendar_response
event_calendar:remove_from_the_calendar_response
event_calendar:settings:group_profile_display:title
event_calendar:settings:group_profile_display_option:left
event_calendar:settings:group_profile_display_option:right
event_calendar:settings:group_profile_display_option:none
event_calendar:settings:agenda_view:title
event_calendar:feature
event_calendar:unfeature
event_calendar:upcoming_events_title
event_calendar:add_user_label
event_calendar:add_user_description
event_calendar:strapline
event_calendar:group_breadcrumb
event_calendar:show_only
event_calendar:listing_title:mine
event_calendar:personal_manage:description
event_calendar:settings:full_calendar:title
event_calendar:basic:header
event_calendar:settings:restricted_times:title
event_calendar:add_event
event_calendar:schedule_event
event_calendar:list_polls
event_calendar:bbb_create_error
event_calendar:bbb_settings_error
event_calendar:river:created
event_calendar:river:updated
event_calendar:river:annotated1
event_calendar:river:annotated2
event_calendar:river:create
event_calendar:river:the_event

Missing strings:

event_calendar:day_label_with_separator
event_calendar:week_label_with_separator
event_calendar:month_label_with_separator
event_calendar:upgrade:success
event_calendar:upgrade:no_updates
event_calendar:admin_notice_pending_upgrades
event_calendar:upgrade
event_calendar:settings:type_list:desc
event_calendar:listing_title:user
event_calendar:upcoming_events_listing_title:all
event_calendar:upcoming_events_listing_title:open
event_calendar:upcoming_events_listing_title:user
event_calendar:upcoming_events_listing_title:friends
event_calander:end_before_start:error
event_calendar:all_day_bit
event_calendar:month:01
event_calendar:month:02
event_calendar:month:03
event_calendar:month:04
event_calendar:month:05
event_calendar:month:06
event_calendar:month:07
event_calendar:month:08
event_calendar:month:09
event_calendar:month:10
event_calendar:month:11
event_calendar:month:12

**Comment by Yaco** [comment]
Just pushed that changes.

**Comment by juho-jaakkola** [comment]
Replaced with #59 that has the same changes, but the commits have been squashed together.

**Pull request closed without merging**
