### PR TITLE
Increase width reserved for labels on event edit page to lessen line-break issue on usage of other languages than English

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
How about we just make the form truly responsive and put labels and inputs on their own lines? What do you think?

**Comment by iionly** [comment]
Getting rid of the table layout would surely work better. I had this idea today, too. But I currently don't have the time to work on it.

**Comment by juho-jaakkola** [comment]
Alternative approach that removes the hard-coded widths completely: #72

**Comment by juho-jaakkola** [comment]
Fixed in #72

**Pull request closed without merging**
