### PR TITLE
Minor UI adjustments with respect to Aalborg theme (still works with default theme)

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
What UI bug does this fix? How can I test it?

**Comment by iionly** [comment]
1. Set "Event listing format" plugin setting to "by month" and view the event list. The list of events and the calendar view should be beside each other. When using the Aalborg theme this wasn't the case because the width of the page content area is smaller with Aalborg theme. Therefore I reduced the width of the event list by 15 px. I think it still looks okay with default theme but now it also works for Aalborg theme. Additionally, I changed it to max-width which comes handy on smaller screens.
2. View the users who have added an event to their personal calendar ("display_user/event_guid"). The buttons of the Aalborg theme are larger than with the default theme. The bottom of the "Remove from calendar" button was on the separator line with Aalborg theme - which I found looked bad. Therefore, I've moved the button slightly up and to the left (position relative).

**Comment by juho-jaakkola** [comment]
1. The fix doesn't work on smaller screens. Suggestions:
   - Use `width: 66%;` for the list and `33%` for the calendar so they work regardless of screen size
   - Move the calendar to sidebar (I think I'd prefer this one)
2. I'd rather use better HTML structure. Either:
   - Add the buttons through entity menu
   - Move the buttons inside `.elgg-image-block`, remove the wrapper, float to right

Also these are clearly separate issues, so could you make an own commit (and PR) for each? (Yesterday I had to debug a major bug on a large Elgg site after upgrading it to 1.11, and I was able to trace down the cause only because Elgg core has such a good changelog.)

**Comment by iionly** [comment]
Calendar view needs a fixed width so it doesn't work with 66/33%. I don't know what you mean regarding the fix not working on smaller screens. I've justed tested again (with Aalborg theme as you need a responsive theme) and it works down to width 360px (and a further reduction is not blocked by the event calendar list view but by other elements on the page).

Putting the calendar into the sidebar could be an option. I've just tested briefly. It seems there would be more work necessary apart from "simply" moving the calendar view output into the sidebar. For example the selection of month/week/day display doesn't work anymore.

These two issues here have in common that they only occur with the Aalborg theme. And they are both really minor fixed. Do you really want me to make separate PRs for each?

**Comment by juho-jaakkola** [comment]
> I don't know what you mean regarding the fix not working on smaller screens.

At some widths the calendar got moved under the event list. But anyway this doesn't really matter if the calendar is moved to sidebar.

> For example the selection of month/week/day display doesn't work anymore [when moved to sidebar].

Sounds like badly designed selectors in the javascript. Those should definitely be changed.

> Do you really want me to make separate PRs for each?

Not necessarily different branches, but definitely different commits. (And it's much easier to manage those if each one has their own PR.) Commit log quality is very important for any kind of software project.

**Comment by iionly** [comment]
> At some widths the calendar got moved under the event list

That's kind of "working as intended". If the calendar would be moved to the sidebar it would be similar as the whole sidebar gets moved to the bottom of the page if the screen width is small.

Calendar view in sidebar seems mainly not working due to the $vars not containing all necessary stuff when the the view is called. Still it might require some more adjustments I currently can't judge yet. Putting the calendar in the sidebar might be the better choice. On the other hand the sidebar is possibly rather full already (owner_block, comments_block, tag_block and possibly other stuff).

But it's simply not a high priority for me at the moment to alter the plugin more than necessary apart from getting its already implemented functionality to work properly at least within a first release. Same with the other open issues (including the notification issues where I currently still hold back the PR). I would much prefer to simply make a release for 1.8 and for 1.9 and then also for 1.10/1.11 (one version necessary for these two versions only). Any further improvements could still be added later on.

**Comment by juho-jaakkola** [comment]
The calendar is too wide for the sidebar, so I ended up using your fix after all: 08b3b9da4039d4610758f949022e3128e7317d76

I fixed the positioning issue by moving the button inside the list item: 2d7c27323a2501ea371e0bc4f595095df17c3712

**Pull request closed without merging**
